# Generated by Django 3.1 on 2020-08-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workshops',
            new_name='Workshop',
        ),
    ]
