# Generated by Django 3.1 on 2020-08-09 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20200809_0407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workshop',
        ),
    ]
